GET http://localhost:5275/buytransactions

###
GET http://localhost:5275/transactions/1

###
POST http://localhost:5275/buytransactions
Content-Type: application/json

{
    "TVendorName": "Kevin Huria",
    "BTquantity": "5",
    "TProductId": "1",
    "TproductName" : "Yellow Mangoes",
    "TBuyPrice" : "60",
    "BuyTransactionDate" : "2024-05-16T05:50:06"
    
}

###


###
DELETE http://localhost:5275/buytransactions/1