GET http://localhost:5275/products

###
GET http://localhost:5275/products/1

###
POST http://localhost:5275/products
Content-Type: application/json

{
    "ProductName": "Final Fantasy XIV",
    "quantity": 2,
    "CategoryID": 4,
    "BuyPrice": 50.00,
    "SellPrice": 60.00,
    "AddedDate": "2024-02-20"
}

###
PUT http://localhost:5275/products/4
Content-Type: application/json

{
    "ProductName": "Final Fantasy XIV",
    "Quantity": 3,
    "CategoryID": 4,
    "BuyPrice": 50.00,
    "SellPrice": 80.00,
    "AddedDate": "2024-02-20"
}

###
DELETE http://localhost:5275/products/4